package assets

import (
	"context"
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"

	"cenarius-autocut/internal/logx"
	"cenarius-autocut/internal/planner"
)

// Titles generated by our own adapters ("Pexels video 123") carry no meaning.
var syntheticTitleRE = regexp.MustCompile(`(?i)^(pexels|pixabay) (video|photo|image) \d+$`)

// Minimum semantic evidence for a stock candidate with a description.
const minStockRelevance = 0.25

// slugText turns a stock page URL into words:
// https://www.pexels.com/video/a-man-typing-on-a-laptop-3129671/ -> "a man typing on a laptop".
func slugText(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return ""
	}
	parts := strings.Split(strings.Trim(u.Path, "/"), "/")
	if len(parts) == 0 {
		return ""
	}
	slug := parts[len(parts)-1]
	words := strings.Split(slug, "-")
	out := words[:0]
	for _, w := range words {
		if w == "" || strings.Trim(w, "0123456789") == "" {
			continue // drop numeric ids
		}
		out = append(out, w)
	}
	return strings.Join(out, " ")
}

// eventAnchors returns the visual anchors of an event, falling back to the
// lexicon and finally to the words of its own queries.
func eventAnchors(e planner.VisualEvent) []string {
	if len(e.Anchors) > 0 {
		return e.Anchors
	}
	if a := planner.ConceptAnchors(e.Concept); len(a) > 0 {
		return a
	}
	seen := map[string]bool{}
	var out []string
	for _, q := range append(append([]string(nil), e.Queries...), e.Concept) {
		for _, w := range tokenize(q) {
			if len(w) >= 3 && !seen[w] {
				seen[w] = true
				out = append(out, w)
			}
		}
	}
	return out
}

// anchorHits counts distinct anchors present in the candidate text.
func anchorHits(anchors []string, text string) int {
	words := map[string]bool{}
	for _, w := range tokenize(text) {
		words[w] = true
		if strings.HasSuffix(w, "s") && len(w) > 3 {
			words[strings.TrimSuffix(w, "s")] = true
		}
	}
	n := 0
	for _, a := range anchors {
		a = strings.ToLower(strings.TrimSpace(a))
		if a != "" && (words[a] || words[a+"s"]) {
			n++
		}
	}
	return n
}

// SemanticScore rates how well a candidate description matches the event.
// It returns the score and whether the candidate passes the relevance gate.
// Candidates without any description (rare) get a neutral score so they can
// still be used, but always after candidates proven relevant.
func SemanticScore(query string, anchors []string, text string) (float64, bool) {
	text = strings.TrimSpace(text)
	if text == "" {
		return 0.30, true
	}
	rel := relevance(query, text, "")
	hits := anchorHits(anchors, text)
	score := rel
	if hits > 0 {
		score = maxF(score, 0.55) + 0.12*float64(minI(hits, 3)-1)
	}
	if score > 1 {
		score = 1
	}
	return score, rel >= minStockRelevance || hits > 0
}

// rankBySemantics drops off-topic stock results and re-ranks the rest by
// meaning first (60%) and by the provider's shape/rank score second (40%).
// This is what stops "technology" from returning random sunsets.
func rankBySemantics(ctx context.Context, provider string, e planner.VisualEvent, query string, cands []Candidate) []Candidate {
	logger := logx.From(ctx)
	anchors := eventAnchors(e)
	out := cands[:0:0]
	for _, c := range cands {
		text := strings.TrimSpace(c.Text)
		if !syntheticTitleRE.MatchString(c.Title) {
			text = strings.TrimSpace(c.Title + " " + text)
		}
		sem, ok := SemanticScore(query, anchors, text)
		if !ok {
			logger.Info("visual.asset.candidate", "provider", provider, "event", e.ID, "accepted", false,
				"reason", "off-topic", "text", truncate(text, 90), "query", query)
			continue
		}
		c.Score = 0.6*sem + 0.4*c.Score
		logger.Debug("visual.asset.candidate", "provider", provider, "event", e.ID, "accepted", true,
			"semantic", fmt.Sprintf("%.2f", sem), "score", fmt.Sprintf("%.2f", c.Score), "text", truncate(text, 90))
		out = append(out, c)
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Score > out[j].Score })
	return out
}

func truncate(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n]) + "…"
}

func maxF(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}

func minI(a, b int) int {
	if a < b {
		return a
	}
	return b
}
